config/routes.rb
RewardBox::Application.routes.draw do

  resources :rewards
  resources :tasks
  
  root to: 'tasks#index'

  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/contact"

  get "static_pages/howitworks"

  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"
  match "/help", to: "static_pages#help"
  match "/howitworks", to: "static_pages#howitworks"

end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessible :content, :user_id, :reward_id, :reward_description
	belongs_to :user
	belongs_to :reward
	validates :content, length: { minimum: 5, :maximum => 140 }

	def recently
		@time = self.created_at
		if @time.to_date == Date.today
			return "Today"
		elsif @time.to_date == Date.yesterday
			return "Yesterday" + " (" +@time.strftime("%A") + ")"
		else
			return @time.strftime("%A")
		end
	end

	def created_at_day
		return self.created_at.wday
	end

end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_filter :require_login, except: [:index]

  def new
    @task = current_user.tasks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  def create
    @task = current_user.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Your task was successfully created! Rock on!' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(tasks_params)
        format.html { redirect_to @task, notice: 'Your task was successfully updated! Rock on!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  def edit
    @task = current_user.tasks.find(params[:id])
  end



  def index
    if user_signed_in?
      @task = current_user.tasks.new
      @tasks = current_user.tasks
      @tasks_this_week = current_user.tasks.where(created_at: (Time.now.beginning_of_week)..(Time.now.beginning_of_week + 7.days))

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @tasks }
      end
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  private

  def require_login
    unless  user_signed_in?
      flash[:error] = "You must be logged in do that. Sorry! Luckily logging in / signing up takes just a sec! =)"
      redirect_to new_user_session_path
    end
  end

  def tasks_params
    params[:task].slice(:content, :reward_description)
  end

end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content, label: 'What did you just get done?', placeholder: "Spent 30 minutes revising a blog post", input_html: { :class => "span9", style: "font-size:1.5em; height:40px" } %>
  <% if @task.reward_id == nil %>
    <% @this_reward = current_user.redeem %>
    <%= f.hidden_field :reward_id, value: @this_reward.id %>
    <%= f.hidden_field :reward_description, value: @this_reward.description %>
    <div class="form-actions">
    <%= f.button :submit, :class => "btn-large btn btn-primary", :value => "Get your reward!" %>

  </div>
  <% else %>
      <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>



<% end %>

app/views/tasks/_task-list.html.erb
<% @monday_tasks, @tuesday_tasks, @wednesday_tasks, @thursday_tasks, @friday_tasks, @saturday_tasks, @sunday_tasks = Array.new(10) { [] } %>

<% @tasks_this_week.each do |task| %>
	<% @tday = task.created_at_day %>
	<% case @tday %>
		<% when 1 %>
			<% @monday_tasks.push(task) %>
		<% when 2 %>
			<% @tuesday_tasks.push(task) %>
		<% when 3 %>
			<% @wednesday_tasks.push(task) %>
		<% when 4 %>
			<% @thursday_tasks.push(task) %>
		<% when 5 %>
			<% @friday_tasks.push(task) %>
		<% when 6 %>
			<% @saturday_tasks.push(task) %>
		<% when 7 %>
			<% @sunday_tasks.push(task) %>
	<% end %>
<% end %>




<div class="main-section" id="explanation">
	<ul id="myTab" class="nav nav-tabs">
	<li class="active"><a href="#monday" data-toggle="tab">Monday (<%= @monday_tasks.length %>)</a></li>
	<li><a href="#tuesday" data-toggle="tab">Tuesday (<%= @tuesday_tasks.length %>)</a></li>
	<li><a href="#wednesday" data-toggle="tab">Wednesday (<%= @wednesday_tasks.length %>)</a></li>
	<li><a href="#thursday" data-toggle="tab">Thursday (<%= @thursday_tasks.length %>)</a></li>
	<li><a href="#friday" data-toggle="tab">Friday (<%= @friday_tasks.length %>)</a></li>
	<li><a href="#saturday" data-toggle="tab">Saturday (<%= @saturday_tasks.length %>)</a></li>
	<li><a href="#sunday" data-toggle="tab">Sunday (<%= @sunday_tasks.length %>)</a></li>
	</ul>




	<div id="myTabContent" class="tab-content">

		<div class="tab-pane fade in active" id="monday">

			<div class="row-fluid">

				<% @monday_tasks.reverse_each do |task| %>
		  			<p><%= link_to task.content, task_path(task), tabindex: "-1" %></p>
		  		<% end %>

			</div>
		</div>


		<div class="tab-pane fade" id="tuesday">


			<div class="row-fluid">

				<% @tuesday_tasks.reverse_each do |task| %>
		  			<p><%= link_to task.content, task_path(task), tabindex: "-1" %></p>
		  		<% end %>

			</div>

		</div>

		<div class="tab-pane fade" id="wednesday">

			<div class="row-fluid" >

				<% @wednesday_tasks.reverse_each do |task| %>
		  			<p><%= link_to task.content, task_path(task), tabindex: "-1" %></p>
		  		<% end %>
			
			</div>

		</div>

		<div class="tab-pane fade" id="thursday">

			<div class="row-fluid" >

			<% @thursday_tasks.reverse_each do |task| %>
	  			<p><%= link_to task.content, task_path(task), tabindex: "-1" %></p>
	  		<% end %>
			
			</div>

		</div>

		<div class="tab-pane fade" id="friday">

			<div class="row-fluid" >

			<% @friday_tasks.reverse_each do |task| %>
	  			<p><%= link_to task.content, task_path(task), tabindex: "-1" %></p>
	  		<% end %>
			
			</div>

		</div>

		<div class="tab-pane fade" id="saturday">

			<div class="row-fluid" >

			<p>Saturday Shit</p>
			
			</div>

		</div>

		<div class="tab-pane fade" id="sunday">

			<div class="row-fluid" >

			<% @sunday_tasks.reverse_each do |task| %>
	  		<%= link_to task.content + " (" + time_ago_in_words(task.created_at) + ")", task_path(task), tabindex: "-1" %>
	  		<% end %>
			
			</div>

		</div>

	</div>

</div>









<br><br>


<div class="accordion-group">
	<div class="accordion-heading">
		<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
	  All Tasks
		</a>
	</div>
	<div id="collapseOne" class="accordion-body collapse">
		<div class="accordion-inner">
			<% @tasks.reverse_each do |task| %>
			<div class="list-task">
			<p><%= task.content %></p>
			<small><%= link_to time_ago_in_words(task.created_at) + " ago", task_path(task) rescue "No date?" %></small>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Task#destroy</h1>
<p>Find me in app/views/task/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Task#edit</h1>
<%= render 'form' %>
<p>
<%= link_to 'Back to Home', tasks_path %>
</p>

app/views/tasks/index.html.erb
<h1>Finish Work -> Get Rewards</h1>
<%= render 'form' %>

<%= link_to "Edit Your Rewards", rewards_path %>

<h3>Completed Tasks</h3>
<% if @tasks %>
	<%= render 'task-list' %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
You completed
<h3><%= @task.content %></h3>
and earned the reward of:

<div class="big-reward">
	<%= @task.reward_description %>
</div>
<p>
	<%= link_to 'Edit this task', edit_task_path(@task) %> | <%= link_to 'Delete this task', @task, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back to Home', tasks_path %>
</p>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>