config/routes.rb
RewardBox::Application.routes.draw do

  resources :rewards
  resources :tasks
  
  root to: 'tasks#index'

  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/contact"

  get "static_pages/howitworks"

  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"
  match "/help", to: "static_pages#help"
  match "/howitworks", to: "static_pages#howitworks"

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :description, :name, :size, :user_id
  belongs_to :user
  has_many :tasks
  validates :description, :length => { minimum: 5, :maximum => 140 }
  # scope :random_of_size, -> (reward_size) { where(size: reward_size).sample }


  def self.test_redeem
    reward_array = []
    reward_array.push(Reward.new(name: "game", description: "Play three rounds of Angry Birds", size: 3))
    reward_array.push(Reward.new(name: "candy", description: "Savor a small piece of dark chocolate.", size: 3))
    reward_array.push(Reward.new(name: "dance", description: "Silent dance party to Gangnam Style. Go!", size: 3))
    reward_array.push(Reward.new(name: "watch", description: "Watch one episode of Game of Thrones.", size: 3))
    reward_array.push(Reward.new(name: "massage", description: "Get on Groupon and book a massage", size: 3))
    reward_array.push(Reward.new(name: "results", description: "Check the results on your favorite team", size: 3))
    reward_array.push(Reward.new(name: "app", description: "Buy the featured game on the App Store", size: 3))
    reward_array.push(Reward.new(name: "HN", description: "Go to HN and pick & read ONE article.", size: 3))
    reward_array.push(Reward.new(name: "TED", description: "Find and watch an interesting TED talk.", size: 3))
    reward_array.push(Reward.new(name: "amazon", description: "Get one thing off your Amazon wishlist.", size: 3))
    reward_array.push(Reward.new(name: "fruit", description: "Find, prepare and eat some fresh fruit.", size: 3))
    reward_array.push(Reward.new(name: "trailer", description: "Watch the trailer for an upcoming flick.", size: 3))
    reward_array.push(Reward.new(name: "nap", description: "Find a dark place and take a 15 min nap.", size: 3))
    reward_array.push(Reward.new(name: "takeout", description: "Order takeout from your favorite restaurant.", size: 3))
    reward_array.push(Reward.new(name: "facebook", description: "Five minutes on Facebook. Set a timer.", size: 3))
    reward_array.push(Reward.new(name: "twitter", description: "Think of something snarky/clever. Tweet it.", size: 3))
    reward_array.push(Reward.new(name: "caffeine", description: "Get yourself some fresh coffee / Red Bull", size: 3))


    random = rand(reward_array.size)-1
    return reward_array[random]
  end

    def self.random_of_size(size)
        return self.where(size: size).sample
    end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # Makes sure they are logged in before they do anything
  before_filter :require_login, except: [:index]
  # GET /rewards
  # GET /rewards.json
  def index
    if user_signed_in?
      @rewards = current_user.rewards.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @rewards }
      end
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = current_user.rewards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = current_user.rewards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = current_user.rewards.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = current_user.rewards.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = current_user.rewards.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(rewards_params)
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = current_user.rewards.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end


  private

  def require_login
    unless  user_signed_in?
      flash[:error] = "You must be logged in do that. Sorry! Luckily logging in / signing up takes just a sec! =)"
      redirect_to new_user_session_path
    end
  end

  def rewards_params
    params[:reward].slice(:name, :description, :size)
  end


end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= simple_form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h3>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :description, placeholder: "Ex: Three rounds of Angry Birds" %>
  <%= f.input :size, collection: 1..3, default: 1 %>
  <div align="left">
    <a href="#" data-toggle="popover" data-original-title="What is the deal with Reward Size?" title data-content= "Size relates to how 'big' the reward is, and thus it's frequency of appearing. Checking Facebook --> 1 (more frequent). Fancy night out --> 3 (less frequent).">What is size?</a>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>





    <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/rewards/_new_reward_partial.html.erb
<div class="big-reward">
	<%= current_user.redeem.description rescue "Use the '+ New Reward' link at the top to make some rewards!" %>
</div>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
  <script>
    function reloadPage() {location.reload()}
  </script>

<% if user_signed_in? %>

  <h3>Good job! Here's your reward: </h3>
  <div class="row">
    <div class="span8">
      <%= render 'rewards/new_reward_partial' %>
    </div>

    <div class="span4">
      <div class="big-reward-button">
       <p><a href="#" class="btn btn-large" value="Show new reward" onclick="reloadPage()">Show new reward <i class="icon-gift icon-3x"></i></a></p>
      </div>
    </div>
  </div>


<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Edit the Rewards here
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <h4><%= link_to 'Create a New Reward', new_reward_path, class: "btn" %></h4>
        <% @rewards.each do |reward| %>
          <div><strong><%= reward.name %></strong> &nbsp; <%= link_to 'Edit', edit_reward_path(reward) %>  &nbsp; | &nbsp;<%= link_to 'Delete', reward, method: :delete, data: { confirm: 'Are you sure?' } %></div>
          <div><%= reward.description %></div>
          <br>
        <% end %>

      </div>
    </div>
  </div>
</div>

<% else %>

<div class="container-narrow" align="center">
  <%= image_tag "/assets/RewardBoxWordmark.png" %>
  <p class="subtitle">A boost of motivation when you've got a not-so-fun job to do</p>
  <div class="big-reward">
    <%= Reward.test_redeem.description %>
  </div>
  <div>
     <p>
      <a href="#" class="btn btn-primary btn-large title-button" value="Get Another Reward" onclick="reloadPage()">Show new reward <i class="icon-gift icon-large icon-white"></i></a>
      <%= link_to "Start your own collection", new_user_registration_path, class: "btn btn-large title-button" %>
     </p>
   </div>
    <br>
   <div class="muted">
    <p align="center">Version 0.8 | (<a href="https://github.com/jasonshen/RewardBox">Github</a>) </p>
  </div>
  <div class="row">
    <br>
    <h1>---- How It Works ----</h1>
    <br>
  </div>
  <div class="row-fluid">
    <div class="span4">
      <%= image_tag "/assets/plusicon.png", class: "align center" %>
      <h3>1) Create Rewards</h3>
      <p>Create a personal collection of activities and things you enjoy.</p>
    </div>
    <div class="span4">
      <%= image_tag "/assets/workicon.png", class: "align center" %>
      <h3>2) Do Some Work</h3>
      <p>Sometimes work isn’t fun. Now you have a little more motivation to get it done.</p>
    </div>
    <div class="span4">
      <%= image_tag "/assets/gifticon.png", class: "align center" %>
      <h3>3) Enjoy Yourself</h3>
      <p>Finished? Great job! Enjoy a guilt-free reward from your collection.</p>
    </div>
  </div>
</div>

<div class="footer muted">
  <div class="container-narrow">
  <h3>About</h3>
  <p>RewardBox is a place to collect and redeem personal incentives to help you take on your least favorite activities.</p>
  <p>It was built by this guy --> <a href="http://twitter.com/jasonshen">@jasonshen</a> who cofounded of a YC startup (<a href="http://ridejoy.com">Ridejoy</a>) and is a budding programmer. Learn more about <%= link_to "RewardBox", about_path %>.<p>
  </div>

</div>

<% end %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reward.name %>
</p>

<p>
  <b>Description:</b>
  <%= @reward.description %>
</p>

<p>
  <b>Size:</b>
  <%= @reward.size %>
</p>

<p>
	<b>User:</b>
	<%= @reward.user.first_name %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>