config/routes.rb
RewardBox::Application.routes.draw do

  resources :rewards
  resources :tasks
  
  root to: 'tasks#index'

  devise_for :users

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/help"

  get "static_pages/contact"

  get "static_pages/howitworks"

  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"
  match "/help", to: "static_pages#help"
  match "/howitworks", to: "static_pages#howitworks"

end

app/views/layouts/_footer.html.erb
<div align="center">
	<%= link_to "About", about_path %> | <%= link_to "Contact", contact_path %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40628428-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_navigation.html.erb
<%= link_to "RewardBox", root_path, class: "brand" %>
<ul class="nav">
	<% if user_signed_in? %>
		<li><%= link_to "+ New Reward", new_reward_path rescue "help!" %></li>
		<li><%= link_to "+ New Task", tasks_path rescue "help!" %></li>

	<% else %>
	<% end %>
</ul>

<ul class="nav pull-right">
	<% if user_signed_in? %>
		<li><%= link_to current_user.full_name, edit_user_registration_path rescue "help!" %></li>
		<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	<% else %>
		<li><%= link_to "Start your collection", new_user_registration_path %></li>
		<li><%= link_to "Sign In", new_user_session_path %></li>
	<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RewardBox" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
      <script type="text/javascript">
      $(function () {
          $('body').popover({
              selector: '[data-toggle="popover"]'
          });

          $('body').tooltip({
              selector: 'a[rel="tooltip"], [data-toggle="tooltip"]'
          });
      });
      </script>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
            <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <button class="close" data-dismiss="alert">x</button>
                  <%= value %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <%= render 'layouts/footer' %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>